[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_VERSION = "22.12.0"
NIXPACKS_NODE_VERSION = "22.12.0"
NIXPACKS_NODE_MAJOR_VERSION = "22"

